name: Draft JOSS Paper

on:
  push:
    paths:
      - 'paper/**'
  workflow_dispatch:

permissions: {}

jobs:
  paper:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Compile JOSS Paper
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - uses: actions/upload-artifact@v7
        with:
          name: paper
          path: paper/paper.pdf
